global_config:
  environment_name: demo
  cloud_platform: existing-ocp
openshift:
- name: cpd-demo
  ocp_version: 4.8
  cluster_name: cpd-demo
  domain_name: example.com
  openshift_storage:
  - storage_name: nfs-storage
    storage_type: nfs
    
cp4d:

- project: cpd-instance
  openshift_cluster_name: cpd-demo
  cp4d_version: 4.0.9
  olm_utils: True
  accept_licenses: True
  cartridges:
  - name: cp-foundation
    license_service:
      state: disabled
      threads_per_core: 2
  - name: lite
  - name: scheduler 
    state: removed

#
# All tested cartridges. To install, change the "state" property to "installed". To uninstall, change the state
# to "removed" or comment out the entire cartridge. Make sure that the "-" and properties are aligned with the lite
# cartridge; the "-" is at position 3 and the property starts at position 5.
#

  - name: analyticsengine 
    size: small 
    state: removed

  - name: bigsql
    state: removed

  # - name: ca
  #   size: small
  #   instances:
  #   - name: ca-instance
  #     metastore_ref: ca-metastore
  #   state: removed

  - name: cde
    state: removed

  - name: datagate
    state: removed

  - name: datastage-ent-plus
    state: removed

  - name: db2
    size: small
    instances:
    - name: ca-metastore
      metadata_size_gb: 20
      data_size_gb: 20
      backup_size_gb: 20  
      transactionlog_size_gb: 20
    state: removed

  - name: db2u
    state: removed

  - name: db2wh
    state: removed

  - name: dmc
    state: removed

  - name: dods
    size: small
    state: removed

  - name: dp
    size: small
    state: removed

  - name: dv
    size: small 
    instances:
    - name: data-virtualization
    state: removed

  - name: hadoop
    size: small
    state: removed

  # - name: mdm
  #   size: small
  #   wkc_enabled: true
  #   state: removed

  - name: openpages
    state: removed

  - name: planning-analytics
    state: removed

  - name: rstudio
    size: small
    state: removed

  - name: spss
    state: removed

  - name: voice-gateway
    replicas: 1
    state: removed

  - name: watson-assistant
    size: small
    state: removed

  - name: watson-discovery
    state: removed

  - name: watson-ks
    size: small
    state: removed

  - name: watson-openscale
    size: small
    state: removed

  - name: watson-speech
    stt_size: xsmall
    tts_size: xsmall
    state: removed

  - name: wkc
    size: small
    state: removed

  - name: wml
    size: small
    state: removed

  - name: wml-accelerator
    replicas: 1
    size: small
    state: removed

  # - name: wsl
  #   state: installed

#
# Cartridges where extra work is needed (will not install automatically)
# 
  # Product Master requires set up of the Db2 instance secret before install
  - name: productmaster
    size: small  
    state: removed


##service addition to the list

  - name: cognos-analytics
    state: removed
    
  - name: cpd-platform
    state: removed

  - name:  datarefinery
    state: removed

  - name: datastage-ent
    state: removed

  - name: db2aaservice
    state: removed

  - name: edb-cp4d
    state: removed

  - name: iis
    state: removed

  - name: informix
    state: removed

  - name: informix-cp4d
    state: removed

  - name: match360
    state: removed

  - name: model-train
    state: removed

  - name: mongodb
    state: removed

  - name: mongodb-cp4d
    state: removed

  - name: openpages-instance
    state: removed

  - name: postgresql
    state: removed

  - name: productmaster-instance
    state: removed

  - name: watson-gateway
    state: removed

  - name: ws
    state: removed

  - name: ws-pipelines
    state: removed

  - name: ws-runtimes
    state: removed

  - name: zen
    state: removed
