global_config:
  environment_name: demo
  cloud_platform: existing-ocp
  env_id: "{{ env_id }}"
  universal_password:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS (Pull registries)
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
  # Create Welcome Cards in AI Manager
  create_cards: true
  # Create App Menu Items in OCP
  create_ocp_items: true
  # Use this Password for all Instances
  global_password: P4ssw0rd!
  # Set this value to True to accept all licenses
  accept_all_licenses: True
  # --------------------------------------------------------------------------------------------------------------------------------------
vault:
  vault_type: file-vault
  vault_authentication_type: none
openshift:
- name: cpd-demo
  ocp_version: '4.10'
  cluster_name: cpd-demo
  domain_name: example.com
  console_banner: "Environment {{ env_id }}"
  openshift_storage:
  - storage_name: auto-storage
    storage_type: auto
